version: 1.0.{build}
image: Visual Studio 2017
build_script:
- cmd: >-
    gradlew build

    IF NOT EXIST build\libs\yammi-1.12.2-b4.jar exit 1

    IF EXIST loader\yammi-1.12.2-b4.jar del /F /Q loader\yammi-1.12.2-b4.jar

    copy build\libs\yammi-1.12.2-b4.jar loader\yammi-1.12.2-b4.jar

    cd loader

    IF EXIST classes.h del /F /Q classes.h

    java -jar packer.jar yammi-1.12.2-b4.jar

    IF EXIST eloader\eloader\classes.h del /F /Q eloader\eloader\classes.h

    copy classes.h eloader\eloader\classes.h

    cd eloader

    msbuild eloader.sln /p:Configuration=Release /p:Platform=x86 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    msbuild eloader.sln /p:Configuration=Release /p:Platform=x64 /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    cd ..\..

    IF EXIST output-total rmdir /S /Q output-total

    mkdir output-total

    copy build\libs\yammi-1.12.2-b4.jar output-total\yammi-1.12.2-b4.jar

    copy loader\eloader\output\Release\yammi-1.12.2-b4.x32.dll output-total\yammi-1.12.2-b4.x32.dll

    copy loader\eloader\output\Release\yammi-1.12.2-b4.x64.dll output-total\yammi-1.12.2-b4.x64.dll

    zip -z output-total\yammi-1.12.2-b4.jar <mainclass.txt
artifacts:
- path: output-total\yammi-1.12.2-b4.jar
  name: main
- path: output-total\yammi-1.12.2-b4.x32.dll
  name: main
- path: output-total\yammi-1.12.2-b4.x64.dll
  name: main
deploy:
- provider: GitHub
  auth_token:
    secure: ypUJqQ52m7lw92mnlk1Ch5t+JZD0skElMNZEFWlSyZn4c2H0GYejPhaKstsBRRzK
  artifact: main
  draft: true
  force_update: true
